---
- hosts:
    - master
    - worker
    - storage
    - workstation
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success

- hosts:
    - rpi
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Install rpi-eeprom
      apt:
        name: rpi-eeprom
        state: latest
    - name: Check reboot
      command: rpi-eeprom-update -a
      register: update_check
    - name: Do Reboot
      reboot:
      when: "'update required' in update_check.stdout"

      