---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: version-v5.21.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # repository: linuxserver/calibre
      # tag: v5.2.0
    env:
      TZ: "America/Los_Angeles"
      PGUID: "${SECRET_UID}"
      PGID: "${SECRET_GID}"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /Shares/Files/
        mountPath: /Files
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
        - host: "calibre.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "calibre.${SECRET_DOMAIN}"
          secretName: calibre
    resources:
      requests:
        memory: 256Mi
    probes:
      startup:
        spec:
          periodSeconds: 15
