kind: Secret
ansible_user: ENC[AES256_GCM,data:HxSDjOtWokkJgw==,iv:kleMmnzwwo1K/472jRPTcHPsXCZANPxEHe0FSmu1MGc=,tag:2N7CMl21vzoy0V08FmkjXw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:41vrpv4M0uR7cEc=,iv:KH15S15V8/1BKyJ7l5/hp2ddrbGzCgh5XnBZVVmkvkw=,tag:2J5Fpion17CEhgvfOo4T2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUY4NEZDRzBDUmx6M2VM
            UVdQWmZsdmRnam9rekl0RWt2d0FPM0RVSEdFCmxXNzhjVEMrVUtITDNuSGVha0Zw
            VXRmSmxVVGFPYmgzYVNLRCtvN1N4UzAKLS0tIDI2K1h0KzJ4WFBUWHVKd1BDbGY4
            dS9tb2J1UVMvc253NnEza2svVUdMYmMKkTPUJen8rT1ykEHW+wsWwhYVz9KnW/Rf
            C6dEhW/ZE4wNqv2sMym3sBpJA9kyhrzo8s+m37tgAWZ1axgi6zjsjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-10T23:02:37Z"
    mac: ENC[AES256_GCM,data:uB+3CEEFZyuPPe1NslERGcH1M64DzmZac3KXHeBneCpRrNPxr4Hzq9pbOvgmDsUFeJydOdNIpp6ueebGcPcm12xVrgd+Qv910CuTNFbWVQYpwv7FXOMJRjgIkXNSb2TGPerzgAadFupgqAjPSzqCCgZiRgdllynCCtVIxMTCHxA=,iv:tGTFUPuwK9ZEr7vhCbUQlQJ/ArOPBoYt0oeZY8dGQqE=,tag:Uch/sAKL3Rz9DCAZXct+4Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
