kind: Secret
ansible_user: ENC[AES256_GCM,data:3qJuMicdLqKX3g==,iv:H4sU4AQoRuptTXCsAuNchhIZYqyehTKS6Qppnr2yS7A=,tag:FcwmUjSYGW/ndCBL5aXmEg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4RPDt/uzBkKhv3U=,iv:BS190cXsyz/180P6DHOdY2BoDc9RkgRm5GYKOAxXmqo=,tag:72xKTAmeukFg7CJIOKDyUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjluVkMvRnJ1djByK2xC
            ay9OR1RPeWxSR1BGZmFvbFNabGZ2ZDZ5VTBZClhlOUFqSGh2MEtkQXFFcWFyaW0w
            TXFtSVZtbnFvUFBpUXBOOVlQQWFBeDgKLS0tIHl3ZjhrNFlJVExjaHpxc2JEeHov
            ZExQdytUT29vMkRvRVFIRGgxVUZXNVkKg8Wbex2HDIyW71NdysJ4Ox8cZVF1VIIa
            4IX+wd0h9ea0AJBbEsSf5kb7vrNQh7qmQvXXo29Oc9oWOurgHsaTzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-12T05:20:56Z"
    mac: ENC[AES256_GCM,data:m4evFX1FOPZXCsSkRTps4/UY1q3yd86Ho0vIphvCt1frexRpYNQeccekEWPtzNHUDkELm434pw5UOFWISy4danMkRCp8LBMLzEO2auyHRz3qpTo/SoZdsQjB54w2rW4GtU4c21f27ceqBVSux+Q8gqERP1B0EKr8cm2D5rgZAp4=,iv:vBGDzaYJFmQ6figBl1P2b+N9fCqMT/oXatCwxvnK53g=,tag:0aQ8CLRh9uY1myCcxaFRCA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
