kind: Secret
ansible_user: ENC[AES256_GCM,data:HzzQ5PrrMq9lag==,iv:eNnrrtYF/5v5QcfZDky+L9E5vyREv6W4KzNudHsSHaA=,tag:5qxNTdCArjasHdDgANvb4Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:66qGEl/Q00xUfhs=,iv:ZekM3NuXPSmea6NDI99wNqVYINJmZ1CNf85V4FwFN5Y=,tag:P8h+1FwXTMiQsjtuDXTh1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaXg2cDBnc2VDZUJoK3FE
            QkpLS1VGL283ZEVoMXh5WTRvNUtONUlQNVFjCnc5NEhqZ0xFK0lOMVdEdE1aSms2
            eitMSUNQQUtVdTFoVVBnUVJzdjRGVFkKLS0tIGFkd2FzUXF2dlVsdGRuZERZSWNv
            bmpXTzQybFVMdjAyR2lTWUkxYUJEMzgKZW6DXpD0MGYw5nB0ZLX5UysKnwK9uhbB
            g3qcH82enH4nmT0eqYuf567SQoUWy7YHxgTjzgkgKttiN1+y+zzUbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-12T05:20:56Z"
    mac: ENC[AES256_GCM,data:IPZ9wT2j4tdWIKcZtSGd1zesAGFOsD/Ncb2gNvKtUuEjnRFMIw9M3BlTw+B0eIjDUuRlPoqRQtfih9f5VwVfzu842X6aCqqHVl4xPKduZej7qrkaima+ng9B+X3I05/QN8IqBXKFTyAwWShOMm/GrN9LapimKDGPIrHEjj5et1Y=,iv:wgWA2H86L5A2aM01kbxZIxAzEXi10HmodMkLiVk5QmY=,tag:92z7/hG9I5MBH8k5JYwx5Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
