---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.50.50.200-10.50.50.250
  METALLB_TRAEFIK_ADDR: 10.50.50.200
  NAS_ADDR: 10.50.50.10
  LB_PLEX_IP: 10.50.50.220
  LB_NEXTCLOUD_IP: 10.50.50.225
