# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpn-gateway-vpnconfig
    namespace: vpn-gateway
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:OYH3SIOcQrC3FxSfDDfO3M4KZS0oeAfzDx3Gc7edABQxDD3Q3TnP+LEp7zuCGfHXB2nFVHErQEEkVkHODRpkSVpyx+4ZbkNd/nA5FECCFdFLFSs9UsfYcJ/xoddC4jyc/uwDIUuIIsh1Ih0gYkxttpuFAyrsIiH0EPEN6hqURG9SN4hSQDuEPz+uUUB597Sl1+txW4qza1IHAGbDnTbkt+n3eMWjlXMlJlEeaDr39QQUBlV73MhjOcDohDcBUmATbCq88SvWpIOpESkCf+YDZnOXPqNg+gsFbujV+xY/ttxXG5XOOOQhE0cP7+r/1lijHFh8uTxV7T7IfmwSZ8hxdAtluKclNGbn+8qQBQQJjD4RHA==,iv:VTlxFER+EqAyLbAZjKr+6AZaN1qfgu65DXmhPZTYkRk=,tag:dzRPpV9ADz1i45GCaU8Plw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWVYrcHVzbmd6M2c5MDFw
            RTd0Z2svRWQzM2VkbmdDazM5RzVGcWFOMW00CndwQmtseVdNVm5uQzdGcXJTNGRv
            eitRZVA2Zm9GUzloSjFtVG8xZlVwdWsKLS0tIFBkYzZvZnhuNmprNXZJclBrT0ls
            T1l5c0IvUjZxL0dBc3FzUTNYYk5aaGMKSOFE5QPIWl5SHo6HmHtE1V99bYnOIMPw
            OivYYGPn7dyoW69biQ8MZUgXIjuHMXxjWcYdYUb06Z2phMeKg11p1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-14T01:17:15Z"
    mac: ENC[AES256_GCM,data:zOMTXRVwQv2A0rI3/RPel8hsHNYfNsbfRctA+BiEuYGqxGSOOOipU1XHP1vtEDR/KaMuygoRHUCBjHLonxBESUv7iwxIdmC4frjNm8lw/cZplVhJe8KUA5V0E3uFXyc/hPB5Cvq3wUC/j5RrBfZPbcDeXfZd8HZNDorS/H/Lzuw=,iv:1j0UxD//Z+n5rkkoa4wGWMwkW8W4Z5og254bHjp7v7g=,tag:HNidhoQ8H18Af8PCU4bXMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
