---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - downloads
  - files
  - kube-system
  - mail
  - media
  - monitoring
  - networking
  - security
  - system-upgrade
  - vpn-gateway
