---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: networking-ak-outpost-radarr
  namespace: networking
spec:
  chain:
    middlewares:
    - name: cloudflare-ips
    - name: networking-ak-outpost-radarr@kubernetescrd
