---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-ak-outpost-sonarr
  namespace: networking
spec:
  chain:
    middlewares:
    - name: cloudflare-ips
    - name: sonarr-downloads-prodromou-com@kubernetes
