---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rook-ceph-block
