---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-v1
  namespace: files
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rook-ceph-block
