---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: version-0.6.13
    env:
      TZ: "America/Los_Angeles"
      PGUID: "${SECRET_UID}"
      PGID: "${SECRET_GID}"
      DOCKER_MODS: "linuxserver/calibre-web:calibre|ghcr.io/gilbn/theme.park:calibre-web"
      TP_THEME: "dracula"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /Shares/Files/
        mountPath: /Files
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
        - host: "books.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "books.${SECRET_DOMAIN}"
          secretName: books
    resources:
      requests:
        memory: 1024Mi
    probes:
      startup:
        spec:
          periodSeconds: 15
