---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-data-v1
  namespace: mail
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-ceph-block
