---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-v1
  namespace: downloads
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block
