---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - downloads.yaml
  - files.yaml
  - media.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - rook-ceph.yaml
  - vpn-gateway.yaml

