---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.7.9
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        host:
          name: "rook.${SECRET_DOMAIN}"
          path: "/"
          pathType: Prefix
        tls:
          - hosts:
            - "rook.${SECRET_DOMAIN}"
            secretName: rook
    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "aprp01"
            devices:
            - name: "sda"
          - name: "aprp02"
            devices:
            - name: "sda"
          - name: "aprp03"
            devices:
            - name: "sda"
          - name: "aprp04"
            devices:
            - name: "sda"
          - name: "aprp05"
            devices:
            - name: "sda"
          - name: "aprp06"
            devices:
            - name: "sda"
          - name: "aprp07"
            devices:
            - name: "sda"
          - name: "aprp08"
            devices:
            - name: "sda"
          - name: "aprp09"
            devices:
            - name: "sda"
          - name: "aprp10"
            devices:
            - name: "sda"
          - name: "aprp11"
            devices:
            - name: "sda"
          - name: "aprp12"
            devices:
            - name: "sda"
    cephObjectStores: []
